const reading = [
    {
        name: "The Fool",
        readings: [
            "Did you press the button? No really I don't know.",
            "What the fuck is a kilometer?",
            "90% of gamblers quit before hitting the jackpot",
            '1 + "1" = "11"',
            "bakamitai...",
            "you should invest in crypto.",
            "I didn't know what to write here, how about you try to write 220 readings smartass.",
            "League of Legends is a good game, definitely.",
            "Yo mama.",
            "I'm literally THE FOOL, what's your excuse?"
        ],
    },
    {
        name: "Death",
        readings: [
            "Ох зря я туда полез.....",
            "You're gonna die..... eventually.",
            "What's the point of life without death? I'm asking you, this is not a rhetorical question.",
            "You should choose JavaScript as your main programming language",
            "If Grim Reaper dies, would Greater Grim Reaper come for his soul?",
            "https://www.youtube.com/watch?v=WqXN_Mv0PJ8",
            "Cats don't have 9 lives, I DO!",
            "RESTLESS was ass.",
            "Let tar consume your being, it's good for the teeth!",
            "There is a landmine somewhere in your house, I don't remember where I put it."
        ],
    },
    {
        name: "Judgement",
        readings: [
            "I know what you did.... psycho.",
            "Best girl in Helltaker, Justice too!",
            "Go outside, open your eyes, look into the sun..... Hurts doesn't it?",
            "Don't judge yourself, judge others.",
            "Fly like a bee, sting like a butterfly.",
            "Be productive, or else...",
            "I really thought this was a good idea, kids, don't be like me.",
            "You SHOULD buy Balatro on steam.",
            "You should NOT buy Killing Floor 3",
            "All the craziest bitches live in Khimki."
        ],
    },
    {
        name: "Justice",
        readings: [
            "Best girl in Helltaker, Judgement too!",
            "It would be a wise decision to dig a big hole in your backyard, trust me bro.",
            "Whatever you're doing, stop that, stinky, dummy, doo doo head, nincompoop.",
            "Prepare for unforseen consequences.... Dr. Freeman...",
            "Be honest with yourself, you don't actually like pistachio ice cream.",
            "Let's be honest, QuadBarrel content was never good and never will be.",
            "Some of the best decisions you will ever make, are the ones when you're drunk.",
            "Your honor, I did NOT in fact, plant a landmine in that person's house.",
            "Guilty, your honor...",
            "Mayonnaise makes everything taste better and you know it."
        ],
    },
    {
        name: "Strength",
        readings: [
            "If you're homeless, just buy a house lol",
            "Steroids are cool actually, if they weren't why would Arnold Schwarzenegger use steroids?",
            "Even at your lowest, you can go lower, start digging.",
            "You don't need to be strong to-.... No, actually, you kinda need to be strong.",
            "Suck it up, we have 219 more dumb jokes to go.",
            "https://www.youtube.com/watch?v=uP7WJ82vqPg",
            "Do not fear anything, except ghosts, ghosts are pretty scary.",
            "Iron Will is THE best perk in Deep Rock Galactic.",
            "Power of the mind fucking sucks, what's that nerd gonna do, math me to death?",
            "When you understand the weakness of flesh, you get more.",
        ],
    },
    {
        name: "Temperance",
        readings: [
            "Maybe instead of buying the 5th energy drink today I could.... Actually no I should get more.",
            "Speed I need this...",
            "Are ya winning, son?",
            "Gungrad will come out.... eventually....",
            "I know temperance is all about patience and shit, but Soda, come on, start making your damn projects.",
            "1 kilogram of feathers is NOT heavier than a kilogram of steel, what are you stupid?",
            "Always remember to sleep at least 23 hours a day!",
            "A perfect harmony is a world without Epic Games.",
            "When are the next Steam sales again?",
            "Wait, this card doesn't actually double my money...",
        ],
    },
    {
        name: "The Chariot",
        readings: [
            "♿",
            "Corola Wagon vroom vroom.",
            "Drunk driving was fun until it became illegal.",
            "The Hermit is NOT the best card.",
            "Ka-chow",
            "x1.5 mult.",
            "No obstacle is great enough, until it can beat you up.",
            "https://www.youtube.com/watch?v=C2Og97q3Qj8",
            "DUDE THESE ANIMALS ARE SO FUCKING FUNNY THEY MAKE ME WANT TO MERGE WITHOUT LOOKING.",
            "Planes are heresy.",
        ],
    },
    {
        name: "The Devil",
        readings: [
            "It's smoko, when I say it's smoko.",
            "https://www.youtube.com/watch?v=oi_fq7rjxAo",
            "mmmmmmm.. nicotina... bueno....",
            "Political_figure.jpg",
            "Yes my son, play those gacha games.... yessss.......",
            "An apple a day keeps all of mankind from heaven.",
            "SHIT PISS FUCK CUNT PUSSY MOTHERFUCKER PENIS ASSHOLE COCK SHIT ASS FUCK",
            "I'm a good guy actually.",
            "Hear me out... Apple is like a forbidden fruit right? So the point is - Mac fucking sucks.",
            "https://www.youtube.com/watch?v=0O1cKedrH3s",
        ],
    },
    {
        name: "The Emperor",
        readings: [
            "https://www.youtube.com/shorts/G_NrkbL9IIg",
            "Rule number 1 - No cursing on the server.",
            "Rule number 2 - No politics in #general.",
            "Rule number 3 - Please do not give birth in VC.",
            "Rule number 4 - Don't tell anyone about the fight club.",
            "Rule number 5 - Follow Discord rules and TOS (Terms of Service).",
            "Rule number 6 - Do not make fun of the moderator team.",
            "Rule number 7 - Keep it SFW.",
            "Rule number 8 - To access the server you MUST sacrifice your first newborn son.",
            "Rule number 9 - No masterbation in VC."
        ],
    },
    {
        name: "The Empress",
        readings: [
            "They told me to just throw shit at the wall until something sticks, IT ALL STICKS WHAT THE FUCK DO I DO???",
            "Denuvo fucking sucks, subscribe to my onlyfans.",
            "Ace is my empress if you kno wha am sayn hahaeeee.",
            "Go on, create, draw, write, I'm not holding a pistol to your head no... It's a shotgun.",
            "https://www.youtube.com/watch?v=EShUeudtaFg",
            "Have you ever thought that giving birth is kinda metal? Like, why is there so much blood.",
            "Enhances 2 selected cards to Mult Cards.",
            "Yo mama.",
            "The Emperor fucking sucks.",
            "💅",
        ],
    },
    {
        name: "The Hanged Man",
        readings: [
            "ARTEMIY IS NOT THE BEST BOY IN RESTLESS AND I'M TIRED OF PRETENDING THAT HE IS!",
            "https://en.wikipedia.org/wiki/Suicide_prevention",
            '"The Tarot Hanged Man card typically represents surrender, patience." - pretty cool huh?',
            '"undefined" - JavaScript 2025 B.C.',
            "Originally I was never going to elaborate on Artemiy's cause of death.",
            "Perhaps it's too late now to change things, but maybe the regret alone is enough.",
            "Don't kill yourself, kill somebody else.",
            '"Suicide is badass!" - Danny Devito',
            "Hope you don't get this one in Phasmaphobia.",
            "Hope you get this one in Balatro.",
        ],
    },
    {
        name: "The Hermit",
        readings: [
            "Money is good, and if you don't like it you should give it to me.",
            "Seek knowledge of important things, like what's money made out of... just between you and me, it's paper.",
            "Be wise and dont waste time on useless gag websites.",
            "Reflect on your past... Actually no, that's physically impossible.",
            "Make better jokes, better than any joke on this website.",
            "My wisdom is - Erik is better than Artemiy.",
            "Don't waste money on gacha games, waste money on Deep Rock Galactic cosmetic DLC's.",
            "I'm so tired...",
            "Focus on your own path and get the fuck out of mine IT'S MINE IT WAS MADE FOR ME IT'S MY PATH!",
            "Congratulations! You got the best card!",
        ],
    },
    {
        name: "The Hierophant",
        readings: [
            "God is watching you, smile.",
            '"The Hierophant tarot card signifies spiritual knowledge" - okay lol?',
            "Go outside, look into the sky and tell God what you did, because if you won't, I will, you psychopath...",
            "Follow the rules, not The Emperor's ones, put your dick into a blender.",
            "Go to college, get a degree, its a good cup coaster.",
            "Legally I'm dead, but its far from what the fact is.",
            "Do NOT invest in crypto.",
            "Why did Jesus turn water into wine? Why not beer?",
            "Praise be to SPACE KING!",
            "The dreamers wish away.",
        ],
    },
    {
        name: "The High Priestess",
        readings: [
            "I GIVE MY LIFE NOT FOR HONOR BUT FOOOOOR YOOOOUUUUUUU",
            "IM STIIIILL IN A DREEEEAAAAAAM SNAAAAKEEE EAAAAAAATEEEEEER",
            "AS THE TALKING GOES IT'S A ONE WAY FLOW",
            "WHEN YOU CAN'T EVEN SAY, MY NAME",
            "Trust yourself more, do a crime.",
            "01110100 01110010 01110101 01110011 01110100 00100000 01111001 01101111 01110101 01110010 00100000 01100111 01110101 01110100 00101100 00100000 01110011 01110100 01101111 01110000 00100000 01110011 01101001 01110100 01110100 01101001 01101110 01100111 00100000 01101111 01101110 00100000 01100100 01110101 01101101 01100010 00100000 01100111 01100001 01100111 00100000 01110111 01100101 01100010 01110011 01101001 01110100 01100101 01110011 ",
            "Isn't it weird that..... No, actually, it's completely normal.",
            "Wait, what is the difference between The Hierophant and The High Priestess, no really I don't get it.",
            "This virtual insanity seems pretty real to me.",
            "Be wise, do not trust anything The Emperor says.",
        ],
    },
    {
        name: "The Lovers",
        readings: [
            "Eve and Samael were never supposed to be actual characters in RESTLESS, I only planned to show them in prologue and never again.",
            '"Love thy neighbor" -  my ass, that asshole is married.',
            "I got a glock in my ra-....We... We got a glock in our rari......",
            "Loves me.",
            "Loves me not.",
            "Kept you waiting huh?",
            "You can love somebody more than anything in the world, but we all know that we love Hideo Kojima even more.",
            "What a thrill.",
            "God loves you, but not as much as he loves Hideo Kojima.",
            "Enhances 1 selected card into a Wild Card.",
        ],
    },
    {
        name: "The Magician",
        readings: [
            "Grace try not to be the worst character in RESTLESS challenge.",
            "Go fish",
            "Skidadle skidoodle your debts are still not paid in full.",
            "Check out this new trick .... DID YOU SEE THAT? DID YOU???",
            "I maybe be The Magician, but writing 220 readings is not magic at all, it's pain.",
            "PSYCHOMANTIS??????",
            "NO THAT IS NOT SOLID SNAKE!",
            "The Magician is the friends we made along the way... lmao no it's not, check this out I can pull a rabbit out of my hat!",
            "God is a magician too in a way.",
            "Hideo Kojima is the true magician."
        ],
    },
    {
        name: "The Moon",
        readings: [
            "The Sun fucking sucks.",
            "Be suspicious of everything, not me though, I'm a cool guy trust me.",
            "I am not in any way associated with the country of Turkey.",
            "I don't get it...",
            "Face your fears... Order that Liquid Snake poster (the sexy one)",
            "Pretty dark out here isn't it?",
            "How can you know that there is nobody standing right behind you? Unless you turn around, then you'll know.",
            "How can we know the moonlanding wasnt faked?",
            "Sun is a star too, so then WHY THE FUCK IS THERE TWO SEPARATE CARDS FOR THE SUN AND THE STAR???",
            "https://www.youtube.com/watch?v=w8VTXoNkHvs&list=RDGMEMHDXYb1_DDSgDsobPsOFxpAVMw8VTXoNkHvs&start_radio=1",
        ],
    },
    {
        name: "The Sun",
        readings: [
            "The Moon fucking sucks.",
            "Pretty bright out here right? You're welcome.",
            "God I hate The Moon, that fucking prick",
            "How fun! Great website isn't it? .... No it's not who am I kidding.",
            "Greatest joy you will ever experience is playing Metal Gear Solid 1.",
            "I see great things coming to you, at an alarming speed too.",
            "I would be happy too... BUT INSTEAD OF ENFORCER WE GOT DRIFTER IN RISK OF RAIN 2 I MEAN COME ON FUCK THOSE STUPID TEMPORARY ITEMS!",
            "https://www.youtube.com/watch?v=JxdiclA0gMQ&list=RDJxdiclA0gMQ&start_radio=1",
            "Love thy neighbor, not The Moon though, fuck that guy.",
            "Be happy, like me! I'm not happy."
        ],
    },
    {
        name: "The Star",
        readings: [
            "Both The Moon and The Sun fucking suck.",
            "https://www.youtube.com/watch?v=z54MpfR3XE4&list=RDz54MpfR3XE4&start_radio=1",
            "I've made peace with the fact that I'm a lowly, stupid, insignificant human who can't do anything right.",
            "Kokichi Oma is better than Nagito and you CANNOT prove me wrong.",
            "PEPSIMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN",
            "Any wound can heal, until its a deadly one, then you'll probably die.",
            "I've fallen.... And I can't get up....",
            "Someone's gotta charge the eels....",
            "Like it or not, you don't know what you're doing.",
            "Hard times can do a number on you, those numbers being bills.",
        ],
    },
    {
        name: "The Tower",
        readings: [
            "Destruction brings creation, unless it's terrorism.",
            "CHAOS! CHAOS!",
            "Why the fuck is there a light tower in a cave?",
            "There was no pizza in the great tower of Pisa, we should destroy it.",
            "Eiffel Tower fucking sucks like why is it even there?",
            "ВАВИЛОН ВАВИЛООООООНБ ЧТО ТЫ ПОСТРОИЛ ЧТО РАЗРУШИЛ",
            "О ЧЕМ ТЫ ГОВОРИШЬ Я ТЕБЯ НЕ ПОНИМАЮ!!!",
            "WHAT ARE THESE DUDES TALKING ABOUT?",
            "JE NE COMPRENDS PAS UN SEUL MOT!",
            "le fromage heh, man it's almost like those french guys have a whole another language."
        ],
    },
    {
        name: "The World",
        readings: [
            "This is nice, yes, good job.",
            "This is good enough.",
            "You win the game!!!",
            "Alas my pook Yorick, he held his head high through it all.",
            "If you don't do anything, you wont fail anything! Except life, you'll fail at life.",
            "Who the fuck stopped time??!!",
            "kono dio da yeah yeah you get the joke whatever.",
            "World is beautiful! Except for Khimki.",
            "YOU DON'T WIN, I DO, I WIN THE GAME, I'M THE WINNER!",
            '"I have a beautiful inner world", bitch have you SEEN Canada?????'
        ],
    },
    {
        name: "Wheel Of Fortune",
        readings: [
            "Keep gambling.",
            "The bigget the bet, the bigger the win.",
            "JUST GIVE ME A FUCKING FLUSH GOD DAMNIT!",
            "My personally favorite card.",
            "50% chance you will have a great time, 50% chance you'll get your cock chopped off.",
            "Wheel of fortune is not about gambling actually.",
            "4 Wheels of fortune on my Chariot, Empress on the backseat, call me The Emperor",
            "90% of gamblers quit before hitting the jackpot",
            "Why is it a wheel again?",
            "You spin my head right round right round.",
        ],
    },
];